const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const genres = [
  "2.5D",
  "2D",
  "2D Fighter",
  "2D Platformer",
  "360 Video",
  "3D",
  "3D Fighter",
  "3D Platformer",
  "3D Vision",
  "4 Player Local",
  "4X",
  "6DOF",
  "8-bit Music",
  "ATV",
  "Abstract",
  "Action",
  "Action RPG",
  "Action RTS",
  "Action Roguelike",
  "Action-Adventure",
  "Addictive",
  "Adventure",
  "Agriculture",
  "Aliens",
  "Alternate History",
  "Ambient",
  "America",
  "Animation & Modeling",
  "Anime",
  "Arcade",
  "Archery",
  "Arena Shooter",
  "Artificial Intelligence",
  "Assassin",
  "Asymmetric VR",
  "Asynchronous Multiplayer",
  "Atmospheric",
  "Audio Production",
  "Auto Battler",
  "Automation",
  "Automobile Sim",
  "BMX",
  "Base Building",
  "Baseball",
  "Basketball",
  "Battle Royale",
  "Beat 'em up",
  "Beautiful",
  "Benchmark",
  "Bikes",
  "Birds",
  "Blood",
  "Board Game",
  "Boomer Shooter",
  "Boss Rush",
  "Bowling",
  "Boxing",
  "Building",
  "Bullet Hell",
  "Bullet Time",
  "CRPG",
  "Capitalism",
  "Card Battler",
  "Card Game",
  "Cartoon",
  "Cartoony",
  "Casual",
  "Cats",
  "Character Action Game",
  "Character Customization",
  "Chess",
  "Choices Matter",
  "Choose Your Own Adventure",
  "Cinematic",
  "City Builder",
  "Class-Based",
  "Classic",
  "Clicker",
  "Co-op",
  "Co-op Campaign",
  "Coding",
  "Cold War",
  "Collectathon",
  "Colony Sim",
  "Colorful",
  "Combat",
  "Combat Racing",
  "Comedy",
  "Comic Book",
  "Competitive",
  "Conspiracy",
  "Conversation",
  "Cooking",
  "Cozy",
  "Crafting",
  "Creature Collector",
  "Cricket",
  "Crime",
  "Crowdfunded",
  "Cult Classic",
  "Cute",
  "Cyberpunk",
  "Cycling",
  "Dark",
  "Dark Comedy",
  "Dark Fantasy",
  "Dark Humor",
  "Dating Sim",
  "Deckbuilding",
  "Demons",
  "Design & Illustration",
  "Destruction",
  "Detective",
  "Dice",
  "Difficult",
  "Dinosaurs",
  "Diplomacy",
  "Documentary",
  "Dog",
  "Dragons",
  "Drama",
  "Driving",
  "Dungeon Crawler",
  "Dungeons & Dragons",
  "Dwarf",
  "Dynamic Narration",
  "Dystopian",
  "Economy",
  "Education",
  "Electronic",
  "Electronic Music",
  "Emotional",
  "Epic",
  "Episodic",
  "Escape Room",
  "Experience",
  "Experimental",
  "Exploration",
  "Extraction Shooter",
  "FMV",
  "FPS",
  "Faith",
  "Family Friendly",
  "Fantasy",
  "Farming",
  "Farming Sim",
  "Fast-Paced",
  "Female Protagonist",
  "Fighting",
  "First-Person",
  "Fishing",
  "Flight",
  "Football (American)",
  "Football (Soccer)",
  "Foreign",
  "Funny",
  "Futuristic",
  "Gambling",
  "Game Development",
  "GameMaker",
  "Games Workshop",
  "Gaming",
  "God Game",
  "Golf",
  "Gore",
  "Gothic",
  "Grand Strategy",
  "Great Soundtrack",
  "Grid-Based Movement",
  "Gun Customization",
  "Hack and Slash",
  "Hacking",
  "Hand-drawn",
  "Hardware",
  "Heist",
  "Hentai",
  "Hero Shooter",
  "Hex Grid",
  "Hidden Object",
  "Historical",
  "Hobby Sim",
  "Hockey",
  "Horror",
  "Horses",
  "Hunting",
  "Idler",
  "Illuminati",
  "Immersive",
  "Immersive Sim",
  "Indie",
  "Instrumental Music",
  "Interactive Fiction",
  "Inventory Management",
  "Investigation",
  "Isometric",
  "JRPG",
  "Jet",
  "Job Simulator",
  "Jump Scare",
  "Kickstarter",
  "LEGO",
  "LGBTQ+",
  "Level Editor",
  "Life Sim",
  "Linear",
  "Local Co-Op",
  "Local Multiplayer",
  "Logic",
  "Loot",
  "Looter Shooter",
  "Lore-Rich",
  "Lovecraftian",
  "MMORPG",
  "MOBA",
  "Magic",
  "Mahjong",
  "Management",
  "Mars",
  "Martial Arts",
  "Massively Multiplayer",
  "Match 3",
  "Mature",
  "Mechs",
  "Medical Sim",
  "Medieval",
  "Memes",
  "Metroidvania",
  "Military",
  "Mini Golf",
  "Minigames",
  "Minimalist",
  "Mining",
  "Mod",
  "Moddable",
  "Modern",
  "Motocross",
  "Motorbike",
  "Mouse only",
  "Movie",
  "Multiplayer",
  "Multiple Endings",
  "Music",
  "Music-Based Procedural Generation",
  "Mystery",
  "Mystery Dungeon",
  "Mythology",
  "NSFW",
  "Narration",
  "Narrative",
  "Nature",
  "Naval",
  "Naval Combat",
  "Ninja",
  "Noir",
  "Nonlinear",
  "Nostalgia",
  "Nudity",
  "Offroad",
  "Old School",
  "On-Rails Shooter",
  "Online Co-Op",
  "Open World",
  "Open World Survival Craft",
  "Otome",
  "Outbreak Sim",
  "Parkour",
  "Parody",
  "Party",
  "Party Game",
  "Party-Based RPG",
  "Perma Death",
  "Philosophical",
  "Photo Editing",
  "Physics",
  "Pinball",
  "Pirates",
  "Pixel Graphics",
  "Platformer",
  "Point & Click",
  "Political",
  "Political Sim",
  "Politics",
  "Pool",
  "Post-apocalyptic",
  "Precision Platformer",
  "Procedural Generation",
  "Programming",
  "Psychedelic",
  "Psychological",
  "Psychological Horror",
  "Puzzle",
  "Puzzle Platformer",
  "PvE",
  "PvP",
  "Quick-Time Events",
  "RPG",
  "RPGMaker",
  "RTS",
  "Racing",
  "Real Time Tactics",
  "Real-Time",
  "Real-Time with Pause",
  "Realistic",
  "Reboot",
  "Relaxing",
  "Remake",
  "Replay Value",
  "Resource Management",
  "Retro",
  "Rhythm",
  "Robots",
  "Rock Music",
  "Roguelike",
  "Roguelike Deckbuilder",
  "Roguelite",
  "Roguevania",
  "Romance",
  "Rome",
  "Rugby",
  "Runner",
  "Sailing",
  "Sandbox",
  "Satire",
  "Sci-fi",
  "Science",
  "Score Attack",
  "Sequel",
  "Sexual Content",
  "Shoot 'Em Up",
  "Shooter",
  "Shop Keeper",
  "Short",
  "Side Scroller",
  "Silent Protagonist",
  "Simulation",
  "Singleplayer",
  "Skateboarding",
  "Skating",
  "Skiing",
  "Sniper",
  "Snow",
  "Snowboarding",
  "Social Deduction",
  "Software",
  "Software Training",
  "Sokoban",
  "Solitaire",
  "Souls-like",
  "Soundtrack",
  "Space",
  "Space Sim",
  "Spaceships",
  "Spectacle fighter",
  "Spelling",
  "Split Screen",
  "Sports",
  "Stealth",
  "Steampunk",
  "Story Rich",
  "Strategy",
  "Strategy RPG",
  "Stylized",
  "Submarine",
  "Superhero",
  "Supernatural",
  "Surreal",
  "Survival",
  "Survival Horror",
  "Swordplay",
  "Tabletop",
  "Tactical",
  "Tactical RPG",
  "Tanks",
  "Team-Based",
  "Tennis",
  "Text-Based",
  "Third Person",
  "Third-Person Shooter",
  "Thriller",
  "Tile-Matching",
  "Time Attack",
  "Time Management",
  "Time Manipulation",
  "Time Travel",
  "Top-Down",
  "Top-Down Shooter",
  "Touch-Friendly",
  "Tower Defense",
  "Trading",
  "Trading Card Game",
  "Traditional Roguelike",
  "Trains",
  "Transhumanism",
  "Transportation",
  "Trivia",
  "Turn-Based",
  "Turn-Based Combat",
  "Turn-Based Strategy",
  "Turn-Based Tactics",
  "Turtle",
  "Twin Stick Shooter",
  "Undead",
  "Underwater",
  "Vampire",
  "Vehicular Combat",
  "Violent",
  "Virtual Reality",
  "Visual Novel",
  "Voxel",
  "Walking Simulator",
  "Wargame",
  "Wargame Sim",
  "Werewolf",
  "Western",
  "Wheelchair Accessible",
  "Whodunit",
  "Wrestling",
  "Zombies",
  "eSports",
];

async function populateGenres() {
  await prisma.genre.createMany({
    data: genres.map((genre) => ({ genreName: genre })),
    skipDuplicates: true,
  });
  console.log("Genres populated successfully!");
}

populateGenres()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
