// extractGenres.js
const { PrismaClient } = require("@prisma/client");
const fs = require("fs");
const prisma = new PrismaClient();
const generateSlug = require("../util/generateSlug");

const genresData = [
  {
    genreName: "Action",
    subgenres: ["Hack & Slash", "Beat 'em up", "Combat", "Spectacle fighter"],
  },
  {
    genreName: "Shooter",
    subgenres: [
      "First-Person Shooter",
      "Third-Person Shooter",
      "Arena Shooter",
      "Extraction Shooter",
      "Tactical Shooter",
      "Movement Shooter",
      "Hero Shooter",
      "Looter Shooter",
      "On-Rails Shooter",
      "Twin Stick Shooter",
      "Top-Down Shooter",
      "Boomer Shooter",
      "Battle Royale",
      "Shoot 'Em Up",
      "Sniper",
      "6DOF",
      "Bullet Hell",
    ],
  },
  {
    genreName: "Platformer & Runner",
    subgenres: [
      "2D Platformer",
      "3D Platformer",
      "Precision Platformer",
      "Puzzle Platformer",
      "Runner",
      "Side Scroller",
      "Metroidvania",
      "Vertical Platformer",
      "Auto Runner",
      "Parkour",
    ],
  },
  {
    genreName: "RPG",
    subgenres: [
      "Action RPG",
      "Strategy RPG",
      "Turn-Based RPG",
      "JRPG",
      "CRPG",
      "Tactical RPG",
      "MMORPG",
    ],
  },
  {
    genreName: "Simulation",
    subgenres: [
      "Building & Automation",
      "City & Settlement",
      "Management",
      "Sports Sim",
      "Racing Sim",
      "Factory Sim",
      "Dating Sim",
      "Farming Sim",
      "Job Sim",
      "Life Sim",
      "Space Flight Sim",
      "Colony Sim",
      "Cooking Sim",
      "Military Sim",
      "Medical Sim",
      "Business Sim",
      "Political Sim",
      "Vehicle Sim",
      "God Game",
      "Hardware Sim",
      "Immersive Sim",
      "Outbreak Sim",
      "Flight Sim",
    ],
  },
  { genreName: "Sandbox", subgenres: ["Physics Sandbox", "Space Sandbox"] },
  {
    genreName: "Strategy",
    subgenres: [
      "Turn-Based Strategy",
      "Wargame",
      "RTS",
      "Grand Strategy",
      "4X",
      "MOBA",
      "Real Time Tactics",
    ],
  },
  {
    genreName: "Card, Board, & Traditional Games",
    subgenres: [
      "Card Game",
      "Card Battler",
      "Deckbuilding",
      "Board Game",
      "Trading Card Game",
      "Tabletop",
      "Dungeons & Dragons",
      "Warhammer 40K",
      "Trivia",
      "Word Game",
      "Dice",
      "Chess",
      "Game Show",
      "Claw Game",
      "Slots",
      "Mahjong",
      "Crossword",
      "Solitaire",
      "Match 3",
    ],
  },
  {
    genreName: "Adventure",
    subgenres: [
      "Point & Click Adventure",
      "Choose Your Own Adventure",
      "Interactive Fiction",
      "Text Adventure",
      "Detective",
      "Investigation",
      "Escape Room",
      "Graphic Adventure",
    ],
  },
  {
    genreName: "Sports",
    subgenres: [
      "Fishing & Hunting",
      "Individual Sports",
      "Team Sports",
      "Baseball",
      "Basketball",
      "Golf",
      "Tennis",
      "ATV",
      "BMX",
      "Bikes",
      "Bowling",
      "Cricket",
      "Cycling",
      "Football (American)",
      "Football (Soccer)",
      "Hockey",
      "Hunting",
      "Motocross",
      "Rugby",
      "Skating",
      "Skiing",
      "Snowboarding",
      "Surfing",
      "Volleyball",
      "eSports",
      "Cue Sports",
      "Track and Field",
      "Wrestling",
    ],
  },
  {
    genreName: "Themes",
    subgenres: [
      "Aliens",
      "Alternate History",
      "America",
      "Anime",
      "Assassin",
      "Cartoon",
      "Cats",
      "Cold War",
      "Conspiracy",
      "Cyberpunk",
      "Dark Fantasy",
      "Demons",
      "Dinosaurs",
      "Dragons",
      "Dystopian",
      "Fantasy",
      "Futuristic",
      "Gothic",
      "Historical",
      "Horror",
      "LGBTQ+",
      "Lovecraftian",
      "Magic",
      "Mars",
      "Mature",
      "Medieval",
      "Military",
      "Modern",
      "Mythology",
      "Nature",
      "Ninja",
      "Noir",
      "Pirates",
      "Post-apocalyptic",
      "Psychological Horror",
      "Rome",
      "Sci-fi",
      "Space",
      "Steampunk",
      "Superhero",
      "Supernatural",
      "Survival Horror",
      "Underground",
      "Underwater",
      "Vampire",
      "Vikings",
      "War",
      "Western",
      "World War I",
      "World War II",
      "Zombies",
    ],
  },
  {
    genreName: "Game Type",
    subgenres: [
      "PvP",
      "PvE",
      "Massively Multiplayer",
      "Team-Based",
      "Co-Operative",
      "LAN",
      "Local & Party",
      "Multiplayer",
      "Online Competitive",
      "Singleplayer",
    ],
  },
  { genreName: "Rhythm", subgenres: [] },
  {
    genreName: "Roguelike",
    subgenres: [
      "Roguelite",
      "Traditional Roguelike",
      "Action Roguelike",
      "Roguelike Deckbuilder",
      "Roguevania",
      "Mystery Dungeon",
    ],
  },
  { genreName: "Racing", subgenres: ["Combat Racing", "Arcade Racing"] },
  { genreName: "Puzzle", subgenres: ["Sokoban", "Hidden Object"] },
  {
    genreName: "Descriptors",
    subgenres: [
      "Gun Customization",
      "Boss Rush",
      "Swordplay",
      "2D",
      "2.5D",
      "3D",
      "Collectathon",
      "Character Customization",
      "Class-Based",
      "Choices Matter",
      "Souls-like",
      "Dungeon Crawler",
      "Turn-Based Combat",
      "Creature Collector",
      "Loot",
      "Perma Death",
      "Open World",
      "Free to Play",
      "Comedy",
      "Funny",
      "Romance",
      "Realistic",
      "Crafting",
      "Survival",
      "Physics-Based",
      "Voxel",
      "Auto Battler",
      "Turn-Based Tactics",
      "Base Building",
      "Diplomacy",
      "Grid-Based Movement",
      "Hex Grid",
      "Multiple Endings",
      "Narrative",
      "Nonlinear",
      "Text-Based",
      "Time Travel",
      "Dynamic Narration",
      "Episodic",
      "Exploration",
      "Mystery",
      "FMV",
      "Story Rich",
      "Visual Novel",
      "Walking Simulator",
      "Clicker",
      "Idler",
      "Casual",
      "Minigames",
      "Education",
      "Family Friendly",
      "Typing",
      "Fast-Paced",
    ],
  },
  {
    genreName: "Fighting",
    subgenres: ["2D Fighting", "3D Fighting", "Martial Arts"],
  },
  { genreName: "Arcade", subgenres: [] },
];

async function repopulateGenres() {
  for (const genreData of genresData) {
    const parentGenre = await prisma.genre.create({
      data: {
        genreName: genreData.genreName,
        parentGenre: null,
      },
    });

    const parentSlug = generateSlug(parentGenre.genreName, parentGenre.id);

    await prisma.genre.update({
      where: { id: parentGenre.id },
      data: { slug: parentSlug },
    });

    for (const subgenre of genreData.subgenres) {
      const childGenre = await prisma.genre.create({
        data: {
          genreName: subgenre,
          parentGenre: parentGenre.id,
        },
      });

      const childSlug = generateSlug(childGenre.genreName, childGenre.id);

      await prisma.genre.update({
        where: { id: childGenre.id },
        data: { slug: childSlug },
      });
    }
  }
}

repopulateGenres();
